spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
  cloud:
    gateway:
      config:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4201"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders:
              - '*'
            exposedHeaders:
              - 'Authorization'
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: psp-payment
          uri: http://localhost:8443/ #lb://psp
          predicates:
            - Path=/payment/**
        - id: psp-payment-method
          uri: http://localhost:8443/ #lb://psp
          predicates:
            - Path=/payment-method/**
        - id: web-users
          uri: http://localhost:8081/
          predicates:
              - Path=/users/**
        - id: web-offers
          uri: http://localhost:8081/
          predicates:
            - Path=/offers/**
        - id: auth-service
          uri: http://localhost:8092 #lb://id-service
          predicates:
            - Path=/id/** #http://localhost:8443/
        - id: paypal
          uri: http://localhost:8083/
          predicates:
            - Path=/paypal
        - id: bitcoin
          uri: http://localhost:8084/
          predicates:
            - Path=/bitcoin

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql:true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/web-shop-db
    username: postgres
    password: ftn
  sql.init:
    platform: postgres
    mode: always

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8089/eureka/
#  main:
#    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance.instance-id: localhost:${server.port}/


logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn

server:
  port: 8091

authentication:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: httptrace
#  httpexchanges:
#    recording:
#      enabled: true

